### ISSUE TITLE
v1.0.2 not work on Chromium 58.0.3029.110

### ISSUE THREAD

**Issue by Explorare** [zbinlin/select2decode#1]
Steps to reproduce the problem:
1. Select a base 64 encoded string;
2. Right click and select decode with extension;

Correct response:
A pop up window show up with decoded result;

What I got:
No pop up window show up.

**Comment by zbinlin** [comment]
Did you reload the page after installed this extension?

**Comment by Explorare** [comment]
I've located the issue. The extension won't convert strings in <textarea>. Take http://base64.us/ for example, the base64 string generated in the `result` <textarea> won't be convert correctly.

**Comment by zbinlin** [comment]
You're right, the extension doesn't supports strings in `input` and `textarea` elements.
